name: documentation build

# This workflow runs on all pull requests because branch protection requires it.
# If no documentation files change, the build steps are skipped to save time.

on:
  pull_request:

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for doc changes
        id: doc_changes
        uses: tj-actions/changed-files@v46
        with:
          files: |
            doc/**/*.rst

      - name: Setup Python
        if: steps.doc_changes.outputs.any_changed == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Sphinx
        if: steps.doc_changes.outputs.any_changed == 'true'
        run: python -m pip install -r doc/requirements.txt

      - name: Build documentation
        if: steps.doc_changes.outputs.any_changed == 'true'
        run: |
          cd doc
          make html SPHINXOPTS="-W -q --keep-going"
